#ifndef _RISCV_SBI_H
#define _RISCV_SBI_H

#define SBI_SET_TIMER 0
#define SBI_CONSOLE_PUTCHAR 1
#define SBI_CONSOLE_GETCHAR 2
#define SBI_CLEAR_IPI 3
#define SBI_SEND_IPI 4
#define SBI_REMOTE_FENCE_I 5
#define SBI_REMOTE_SFENCE_VMA 6
#define SBI_REMOTE_SFENCE_VMA_ASID 7
#define SBI_SHUTDOWN 8

// Monitor API

// SM CALLS FROM ENCLAVE (from U-mode, within an enclave)
#define UBI_SM_ENCLAVE_BLOCK_DRAM_REGION      1000

#define UBI_SM_ENCLAVE_CHECK_OWNERSHIP        1001

#define UBI_SM_ENCLAVE_ACCEPT_THREAD          1002

#define UBI_SM_ENCLAVE_EXIT_ENCLAVE           1003

#define UBI_SM_ENCLAVE_GET_ATTESTATION_KEY    1004

#define UBI_SM_ENCLAVE_ACCEPT_MESSAGE         1005
#define UBI_SM_ENCLAVE_READ_MESSAGE           1006
#define UBI_SM_ENCLAVE_SEND_MESSAGE           1007

// SM CALLS FROM OS (these come from S-mode)
#define SBI_SM_OS_BLOCK_DRAM_REGION           2000

#define SBI_SM_OS_SET_DMA_RANGE               2001

#define SBI_SM_OS_DRAM_REGION_STATE           2002
#define SBI_SM_OS_DRAM_REGION_OWNER           2003
#define SBI_SM_OS_ASSIGN_DRAM_REGION          2004
#define SBI_SM_OS_FREE_DRAM_REGION            2005
#define SBI_SM_OS_FLUSH_CACHED_DRAM_REGIONS   2006

#define SBI_SM_OS_CREATE_METADATA_REGION      2007
#define SBI_SM_OS_METADATA_REGION_PAGES       2008
#define SBI_SM_OS_METADATA_REGION_START       2009
#define SBI_SM_OS_THREAD_METADATA_PAGES       2010
#define SBI_SM_OS_ENCLAVE_METADATA_PAGES      2011

#define SBI_SM_OS_CREATE_ENCLAVE              2012
#define SBI_SM_OS_LOAD_PAGE_TABLE             2013
#define SBI_SM_OS_LOAD_PAGE                   2014
#define SBI_SM_OS_LOAD_THREAD                 2015
#define SBI_SM_OS_ASSIGN_THREAD               2016
#define SBI_SM_OS_INIT_ENCLAVE                2017

#define SBI_SM_OS_ENTER_ENCLAVE               2018

#define SBI_SM_OS_DELETE_THREAD               2019

#define SBI_SM_OS_DELETE_ENCLAVE              2020

#define SBI_SM_OS_COPY_DEBUG_ENCLAVE_PAGE     2021

#endif
